### ISSUE TITLE
FlushBar error on Flutter 2.10.2 'entry.currentState == _RouteLifecicle.popping......'

### ISSUE THREAD

**Issue by davidfranquet** [cmdrootaccess/another-flushbar#58]
Flushbar is crashing on Flutter 2.10.+ 

Here is the log:

`Failed assertion: line 5021 pos 12: 'entry.currentState == _RouteLifecycle.popping ||
          (entry.hasPage && entry.currentState.index < _RouteLifecycle.pop.index)': is not true.
flutter: #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      NavigatorState.finalizeRoute (package:flutter/src/widgets/navigator.dart:5021:12)
#3      OverlayRoute.didPop (package:flutter/src/widgets/routes.dart:74:18)
#4      FlushbarRoute.didPop (package:another_flushbar/flushbar_route.dart:393:18)
#5      _RouteEntry.handlePop (package:flutter/src/widgets/navigator.dart:2896:16)
#6      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3860:22)
#7      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4902:7)
#8      FlushbarRoute._configureTimer.<anonymous closure> (package:another_flushbar/flushbar_route.dart:403:22)
#9      _rootRun (dart:async/zone.dart:1418:47)
#10     _CustomZone.run (dart:async/zone.dart:1328:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#13     _rootRun (dart:async/zone.dart:1426:13)
#14     _CustomZone.run (dart:async/zone.dart:1328:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
#16     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
`

**Comment by alexaniko88** [comment]
Same here!

**Comment by walsha2** [comment]
Also getting this issue... not sure what is going on or how to resolve it.

**Comment by juliansteenbakker** [comment]
This is a bug in Flutter https://github.com/flutter/flutter/issues/98224

**Comment by alexaniko88** [comment]
> 

Not really, as they say:
_The Route.didPop is not meant to be called directly, you should use Navigator.pop instead_

**Comment by juliansteenbakker** [comment]
Yes and further:

> The removed route is removed without being completed, so this method does not take a return value argument. 
> The places where I am using didPop to close a route are passing values back to the widget which displayed them. If there is a way of doing that, please let me know.

Also, the Route.didPop thats implemented in FlushbarRoute is an extended class of OverlayRoute, which is part of the Flutter framework and also uses Route.didPop, so the error is part of the Flutter Framework and not this package.

**Comment by danken00** [comment]
Happening for me too. I'm also a bit confused as to why FlushBar is doing anything with Routes in the first place... what's the relationship? But yes, it's crashing everything; commenting out the FlushBar causes the issue to go away.

**Comment by orevial** [comment]
I have the same issue on Flutter 2.10.5 but in my case it's only happening when the flushbar is started while the app is in background.

Basically I have a BLoC listener that triggers a flushbar on some events (e.g. connectivity change). When the flushbar is started there is no problem but when the flushbar is dismissed I get the above exception when it was started in background. 

Steps to reproduce : 
- Register a listener on some event that will display the flushbar while the app is in background (not shown)
- Put the app in the background
- Trigger the event that will make the listener display the flushbar (e.g. a connectivity change)
- Wait for the end of timer duration
- The exception is thrown

**Comment by KubanychAsanov** [comment]
any updates?

**Comment by Davete0302** [comment]
any fix or workaround?

**Comment by ercantomac** [comment]
Any updates on this? It's a pretty serious issue

**Comment by nicolobozzato** [comment]
Don't if it can help you, but I found it happens when you pop a route after call show on a flushbar.
So you can either await for it to finish and then pop, or also wrapping it in a 
`Future.delayed(Duration.zero, (){
});`

works, so it schedules it right after the pop and doesn't tries to pop the flushbar WHILE you are popping the route giving the error.

**Comment by NicoloBozzatoWashOut** [comment]
i regret to inform that the solution with Future.delayed still doesn't resolve the issue in some instances

**Comment by nicolobozzato** [comment]
I regret to inform you that my solution with Future.delayed still doesn't resolve the issue in some instances

**Comment by JPLeoRX** [comment]
Encountered this issue too, are there any updates or workarounds? This is a quite severe issue in an otherwise perfect library.

**Comment by moloti** [comment]
I also have this issue

**Comment by DenisAnkh** [comment]
The simplest way to fix the bug replace `didPop()` in `FlushbarRoute` with the following:

```dart
 @override
  bool didPop(T? result) {
    assert(_controller != null,
        '$runtimeType.didPop called before calling install() or after calling dispose().');
    assert(!_transitionCompleter.isCompleted,
        'Cannot reuse a $runtimeType after disposing it.');

    _result = result;
    _cancelTimer();

    if (_wasDismissedBySwipe) {
      Timer(const Duration(milliseconds: 200), () {
        _controller!.reset();
      });

      _wasDismissedBySwipe = false;
      return super.didPop(result);
    } else {
      final duration = flushbar.duration ?? const Duration(milliseconds: 2000);
      Timer(duration, () => _controller!.reverse());
    }

    return super.didPop(result);
  }
```

**Comment by reynirf** [comment]
This issue is still occurring and crashing my app.

**Comment by DevTiago** [comment]
**_Same here!_**

**Comment by hodfords-khai-mobile** [comment]
same issue

**Comment by fuadreza** [comment]
Any update on this?

**Comment by fuadreza** [comment]
> I have the same issue on Flutter 2.10.5 but in my case it's only happening when the flushbar is started while the app is in background.
> 
> Basically I have a BLoC listener that triggers a flushbar on some events (e.g. connectivity change). When the flushbar is started there is no problem but when the flushbar is dismissed I get the above exception when it was started in background.
> 
> Steps to reproduce :
> 
> * Register a listener on some event that will display the flushbar while the app is in background (not shown)
> * Put the app in the background
> * Trigger the event that will make the listener display the flushbar (e.g. a connectivity change)
> * Wait for the end of timer duration
> * The exception is thrown

So My temporary solution for this was to monitor app lifecycle and add condition using `WidgetsBindingObserver` to check whether the app is in foreground or not. If not, it will not trigger the flushbar.
```dart

  bool isInForeground = true;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  /// Called when the app lifecycle state changes.
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    isInForeground = state == AppLifecycleState.resumed;
  }

```
Then on your flushbar trigger
```dart

if (isInForeground) {
   // SHOW FLUSHER
}
```
